# Generated by Django 5.1.2 on 2024-11-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FR", "French"),
                            ("US", "American"),
                            ("IT", "Italian"),
                            ("JP", "Japanese"),
                            ("CH", "Chinese"),
                            ("BR", "Brazilian"),
                            ("IN", "Indian"),
                            ("DE", "German"),
                            ("ES", "Spanish"),
                            ("GB", "British"),
                            ("MX", "Mexican"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
